web/router.ex
defmodule Once.Router do
  use Once.Web, :router

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  scope "/api", Once, as: :api do
    pipe_through(:api)

    post("/create", API.SecretController, :create)
    get("/show/:slug/:key", API.SecretController, :show)
  end

  scope "/", Once do
    pipe_through(:browser)

    get("/", HTML.SecretController, :new)
    post("/create", HTML.SecretController, :create)
    get("/show/:slug/:key", HTML.SecretController, :show)
    get("/gate/:slug/:key", HTML.SecretController, :gate)
    get("/gone", HTML.SecretController, :gone)
  end
end

lib/once/endpoint.ex
defmodule Once.Endpoint do
  use Phoenix.Endpoint, otp_app: :once

  socket("/socket", Once.UserSocket)

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug(Plug.Static,
    at: "/",
    from: :once,
    gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)
  )

  #  # Code reloading can be explicitly enabled under the
  #  # :code_reloader configuration of your endpoint.
  #  if code_reloading? do
  #    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
  #    plug Phoenix.LiveReloader
  #    plug Phoenix.CodeReloader
  #  end

  plug(Plug.RequestId)
  plug(Plug.Logger)

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug(Plug.Session,
    store: :cookie,
    key: "_once_key",
    signing_salt: "1QAf40oZ"
  )

  plug(Once.Router)
end

lib/once/repo.ex
defmodule Once.Repo do
  use Ecto.Repo, otp_app: :once
end

web/models/secret.ex
defmodule Once.Secret do
  use Once.Web, :model

  alias Once.Repo
  import Once.Bcrypt, only: [hash_key: 1]

  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}

  schema "secrets" do
    field(:cipher_text, :string)
    field(:slug, :string, unique: true)
    field(:key_hash, :string)
    field(:key, :string, virtual: true)

    timestamps()
  end

  @required_fields ~w(cipher_text key)

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required_fields)
    |> hash_key
    |> put_change(:slug, new_slug())
    |> validate_required([:cipher_text, :slug, :key_hash])
  end

  defp new_slug do
    slug = MnemonicSlugs.generate_slug(Application.get_env(:once, :slug_length))

    case Repo.get_by(Once.Secret, slug: slug) do
      {:ok, _secret} -> new_slug()
      nil -> slug
    end
  end
end

web/controllers/api/fallback_controller.ex
defmodule Once.API.FallbackController do
  use Once.Web, :controller

  def call(conn, {:error, %changeset{}}) do
    conn
    |> put_status(:unprocessable_entity)
    |> render("errors.json", messages: changeset.errors)
  end

  def call(conn, {:error, _message}) do
    conn
    |> put_status(:not_found)
    |> render("errors.json", messages: ["This link has expired or never existed"])
  end
end

web/controllers/api/secret_controller.ex
defmodule Once.API.SecretController do
  use Once.Web, :controller

  action_fallback(Once.API.FallbackController)

  alias Once.{AES, Repo, Secret}

  def create(conn, %{"secret" => raw_params}) do
    secret_params = AES.encrypt(raw_params["plain_text"])
    changeset = Secret.changeset(%Secret{}, secret_params)

    with {:ok, secret} <- Repo.insert(changeset) do
      link = api_secret_url(conn, :show, secret.slug, secret.key)

      conn
      |> put_status(:created)
      |> render("create.json",
        secret: %{key: secret_params.key, slug: secret.slug, link: link}
      )
    end
  end

  def show(conn, %{"slug" => slug, "key" => key}) do
    with :ok <- confirm_existence_of(slug, key),
         {:ok, secret} <- secret_from_slug(slug),
         {:ok, plain_text} <- AES.decrypt(secret.cipher_text, key) do
      Repo.delete(secret)

      conn
      |> render("show.json", plain_text: plain_text)
    end
  end

  defp secret_from_slug(slug) do
    case Repo.get_by(Secret, slug: slug) do
      nil -> {:error, :invalid_slug_or_key}
      %Once.Secret{} = secret -> {:ok, secret}
    end
  end

  defp confirm_existence_of(slug, key) do
    case !slug || !key do
      true -> {:error, :invalid_slug_or_key}
      false -> :ok
    end
  end
end

web/controllers/html/fallback_controller.ex
defmodule Once.HTML.FallbackController do
  use Once.Web, :controller

  def call(conn, {:error, %changeset{}}) do
    conn
    |> put_flash(:error, "We could not create your secret.")
    |> render("new.html", changeset: changeset)
  end

  def call(conn, {:error, _message}) do
    conn
    |> redirect(to: secret_path(conn, :gone))
  end
end

web/controllers/html/secret_controller.ex
defmodule Once.HTML.SecretController do
  use Once.Web, :controller

  action_fallback(Once.HTML.FallbackController)

  alias Once.{AES, Repo, Secret}

  def new(conn, _params) do
    changeset = Secret.changeset(%Secret{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"secret" => raw_params}) do
    secret_params = AES.encrypt(raw_params["plain_text"])
    changeset = Secret.changeset(%Secret{}, secret_params)

    with {:ok, secret} <- Repo.insert(changeset) do
      conn
      |> render("confirm.html",
        key: secret_params.key,
        slug: secret.slug,
        plain_text: raw_params["plain_text"]
      )
    end
  end

  def gate(conn, %{"slug" => slug, "key" => key}) do
    conn
    |> render("gate.html", slug: slug, key: key)
  end

  def show(conn, %{"slug" => slug, "key" => key}) do
    with :ok <- confirm_existence_of(slug, key),
         {:ok, secret} <- secret_from_slug(slug),
         {:ok, plain_text} <- AES.decrypt(secret.cipher_text, key) do
      Repo.delete(secret)

      conn
      |> render("show.html", plain_text: plain_text)
    end
  end

  def gone(conn, %{}) do
    conn
    |> render("gone.html")
  end

  defp secret_from_slug(slug) do
    case Repo.get_by(Secret, slug: slug) do
      nil -> {:error, :invalid_slug_or_key}
      %Once.Secret{} = secret -> {:ok, secret}
    end
  end

  defp confirm_existence_of(slug, key) do
    case !slug || !key do
      true -> {:error, :invalid_slug_or_key}
      false -> :ok
    end
  end
end

web/views/error_view.ex
defmodule Once.ErrorView do
  use Once.Web, :view

  def render("404.html", _assigns) do
    # "Page not found"
    render("error.html", %{})
  end

  def render("500.html", _assigns) do
    # "Internal server error"
    render("error.html", %{})
  end

  def render("error.json", %{messages: messages}) do
    %{errors: messages}
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render("500.html", assigns)
  end
end

web/views/html/secret_view.ex
defmodule Once.HTML.SecretView do
  use Once.Web, :view
end

web/views/layout_view.ex
defmodule Once.LayoutView do
  use Once.Web, :view
end

web/views/secret_api_view.ex
defmodule Once.SecretAPIView do
  use Once.Web, :view

  def render("create.json", %{secret: secret}) do
      %{secret: render_one(secret, Once.SecretAPIView, "secret.json", as: :secret)}
  end

  def render("show.json", %{plain_text: plain_text}) do
    %{plain_text: plain_text}
  end

  def render("secret.json", %{secret: secret}) do
    %{key: secret.key,
      slug: secret.slug,
      link: secret.link}
  end

  def render("errors.json", %{messages: messages}) do
    %{errors: messages}
  end
end

web/templates/html/secret/confirm.html.eex
<div class="container">
  <div class="content text-center">
    <h3 class="headline">Your One Time Link</h3>
    <p>Visiting that link once will make it disappear!</p>
  </div>

  <div class="well link-well text-center">
    <code class="fake-link"><%= secret_url(@conn, :gate, @slug, @key) %></code>
  </div>
  <div class="text-center">
    
    <p><em>Want to double check? You can see your secret one more time if you need to.</em></p>
  </div>

  <div class="secret-container text-center">
    <input type="checkbox" id="show_secret" role="button">
    <label class="btn btn-default" for="show_secret" onclick=""><span>Show the Secret Again</span><span>Hide Secret</span></label>

    <section class="secret-section">
      <div class="secret-well well">
        <%= @plain_text %>
      </div>
    </section>  
  </div>​
</div>

web/templates/html/secret/gate.html.eex
<div class="container">
  <div class="text-center">
    <h3 class="headline">You Have a Secret!</h3>
    <p>Click the button to activate the one time link and see the secret</p>
    <%= link "View my Secret", to: secret_url(@conn, :show, @slug, @key), class: "btn btn-primary" %>
  </div>
</div>

web/templates/html/secret/gone.html.eex
<div class="container">
  <div class="text-center">
    <h3 class="headline">This secret is gone or perhaps never existed!</h3>
    <p>Each link is only useful once. If it's been visited, the content is gone forever. You are also redirected here if you provide bad info even if a link was never here</p>
    <br/>
    <div class="">
      <p>Have something to share?</p>
      <%= link "Share a Secret", to: secret_path(@conn, :new), class: "btn btn-default" %>
    </div>
  </div>
</div>

web/templates/html/secret/new.html.eex
<div class="section">
  <div class="container">
    <div class="text-center">
      <h1 class="headline">Share a Secret. Once</h1>
      <p>Encrypt it and get a one time link to share with someone else</p>
    </div>
    <div class="row">
      <div class="col-sm-offset-2 col-sm-8">
        <%= form_for @changeset, secret_path(@conn, :create), fn f -> %>
          <div class='form-group'>
            <%= textarea f, :plain_text,
                            [class: "form-control secret-textarea",
                             required: true] %>
          </div>

          <div class="text-center">
            <%= submit "Create a Secret Link", [class: "btn btn-primary"] %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="hiw-panel text-center">
  <div class="row">
    <h1 class="hiw-title">How It Works</h2>
    <div class="hiw-step col-sm-6 col-md-3">
      <h2>Encrypt a Secret</h2>
      <img src="/images/encrypt.svg">
      <p>When you provide a secret Otaoto encrypts it with a new random secure key and stores that encrypted text. Otaoto also stores a hash of the key so later it can confirm the key without actually knowing what it is</p>
    </div>
    <div class="hiw-step col-sm-6 col-md-3">
      <h2>Create a Link</h2>
      <img src="/images/create-link.svg">
      <p>A link contains two parts, a three word sequence and the decryption key. The three word sequence to identify which secret it is. Since we don't store that key at all, the key in your link is your only copy </p>
    </div>
    <div class="hiw-step col-sm-6 col-md-3">
      <h2>Open the Link</h2>
      <img src="/images/open-link.svg">
      <p>When you visit a link with a secret, Otaoto confirms that there is a secret with that three word sequence and checks to make sure the right key is present</p>
    </div>
    <div class="hiw-step col-sm-6 col-md-3">
      <h2>Destroy the Secret</h2>
      <img src="/images/burn-secret.svg">
      <p>If all the correct information is present, Otaoto deletes everything from the database, then sends the decrypted text to you. Everything has been deleted, that link will never be usable again</p>
    </div>
  </div>
</div>

web/templates/html/secret/show.html.eex
<div class="container">
  <div class="text-center">
    <h3 class="headline">Here's a Secret</h3>
    <p>Put it somewhere safe! It was already deleted from the database</p>
    <div class="well secret-well view-secret">
      <%= @plain_text %>
    </div>
    <br />
    <div>
      <p>Have something to share?</p>
      <%= link "Share a Secret", to: secret_path(@conn, :new), class: "btn btn-default" %>
    </div>
  </div>
</div>

web/templates/secret/gate.eex
<div class="container">
  <div class="text-center">
    <h3 class="headline">You Have a Secret!</h3>
    <p>Click the button to activate the one time link and see the secret</p>
    <%= link "View my Secret", to: secret_url(@conn, :show, @slug, @key), class: "btn btn-primary" %>
  </div>
</div>